# Generated by Django 3.2.16 on 2022-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='תאריך החזרה')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='שם')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='מקום')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='הערות')),
                ('pack', models.IntegerField(blank=True, null=True, verbose_name='חליפות')),
                ('coat', models.IntegerField(blank=True, null=True, verbose_name='מעילים')),
                ('pants', models.IntegerField(blank=True, null=True, verbose_name='מכנסיים')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון')),
                ('done', models.BooleanField(default=False, verbose_name='הוחזר')),
            ],
        ),
    ]
