# Generated by Django 3.2.16 on 2022-12-29 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_date', models.DateTimeField(blank=True, editable=False)),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='תאריך החזרה')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='שם')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='מקום')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='הערות')),
                ('pack', models.IntegerField(blank=True, null=True, verbose_name='חליפות')),
                ('coat', models.IntegerField(blank=True, null=True, verbose_name='מעילים')),
                ('pants', models.IntegerField(blank=True, null=True, verbose_name='מכנסיים')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='טלפון')),
                ('done', models.BooleanField(default=False, verbose_name='הוחזר')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
