# Generated by Django 3.2.16 on 2025-01-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_historicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('רשפון', 'רשפון'), ('נשר', 'נשר')], default='רשפון', max_length=20),
        ),
    ]
